prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  service:
    type: NodePort
grafana:
  enabled: true
  service:
    type: NodePort
  adminUser: admin
  adminPassword: password753
  # dashboardProviders:
  #   dashboardproviders.yaml:
  #     apiVersion: 1
  #     providers:
  #     - name: 'trivy-dashboard-provider'
  #       orgId: 1
  #       folder: ''
  #       type: file
  #       disableDeletion: false
  #       editable: false
  #       options:
  #         path: /var/lib/grafana/dashboards/trivy
  # dashboards:
  #   trivy-dashboard-provider:
  #     trivy:
  #       datasource: Prometheus
  #       gnetId: 17813
  #       revision: 1
alertmanager:
  enabled: true
  service:
    type: NodePort
