apiVersion: v1
kind: Pod
metadata:
  name: my-suboptimal-pod
  # annotations:
  #   container.apparmor.security.beta.kubernetes.io/my-ubuntu: localhost/my-apparmor-profile
spec:
  terminationGracePeriodSeconds: 0
  # automountServiceAccountToken: false
  # securityContext: 
  #   seccompProfile: # <= uncomment this line
  #     type: Localhost # <= uncomment this line
  #     localhostProfile: profiles/my-profile.json # <= uncomment this line
  #   appArmorProfile: # <= uncomment this line on k8s > v1.31
  #     type: Localhost # <= uncomment this line on k8s > v1.31
  #     localhostProfile: my-apparmor-profile # <= uncomment this line on k8s > v1.31
  containers:
    - name: my-ubuntu
      image: ubuntu
      args: ["sleep", "1d"]
      securityContext:
        readOnlyRootFilesystem: false
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0 # 65534
        runAsNonRoot: false
      # resources:
      #   requests:
      #     cpu: "0.5"
      #     memory: "256Mi"
      #   limits:
      #     cpu: "0.5"
      #     memory: "256Mi"
      volumeMounts:
        - name: host
          mountPath: /host/
          # readOnly: true
        # - name: secret-data
        #   mountPath: /secret/
        #   readOnly: true
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
    # - name: secret-data
    #   secret:
    #     secretName: my-secret
